language: node_js
node_js:
  - "4"
addons:
  ssh_known_hosts: szadam.hu
install:
  - npm install
  - npm install -g gulp
  - npm install -g bower
  - bower install
script:
  - gulp build

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/dist $RSYNC_USER@$HOST:$RSYNC_FOLDER
  on:
    branch: master